config/routes.rb
Rails.application.routes.draw do
#Setting it as "home" page for the server
  root "todos#index"
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #using "todos" mode
resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

     def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
     end
end

def create 
  @todo = current_user.todos.new(todo_params)
    if @todo.save
      flash[:success] = "To Do Created"
      redirect_to todos_path
    else
      flash[:error] = "Error #{@todo.errors.full_messages.join('\n')}"
      render :new
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update]

  def index
    @todos = current_user.todos
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = current_user.todos.new(todo_params)
    if @todo.save
      redirect_to todos_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      redirect_to todos_path
    else 
      render :edit
    end
  end

  def destroy
    @todo.destroy
    redirect_to todos_path
  end

  private
    def todo_params
      params.require(:todo).permit(:name, :status, :task)
    end

    def set_todo

      #note: it was not in the instructor's code, but as per mentioned in LMS, going to 
      #add it here to see what the result would be. 

      @todo = current_user.todos.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" ><%= value %> </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h3>Edit To-Do Task</h3>
<%= form_with(model: @todo, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Task Name" %>
  </div>
    <div class="field">
    <%= f.label :name %>
    <%= f.text_field :task, required: true, placeholder: "Task Description" %>
  </div>
<!--- find out how to make a dropdown list here -->
    <div class="field">
    <%= f.label :status %>
   <!-- > <%= f.text_field :status, required: true, placeholder: "Status" %> -->
    <%= f.select :status, options_for_select(['Pending','Work in Progress','Done']), {}, {class: 'browser-default'} %> <br>
    </div> 
  <%= f.submit %>
  <% end %>

app/views/todos/index.html.erb
<h2>Welcome <%= current_user.first_name %></h2>
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<%= link_to "Add To-Do Task", new_todo_path %>
<h3>Your To-Do list</h3>
<ul>
 <% @todos.each do |todo| %>
 <li>
 <%= todo.name %> - <%= todo.task %> - <%= todo.status %>
 <%= link_to "Edit Task", edit_todo_path(todo) %>
 </li>
 <% end %>
 </ul>

app/views/todos/new.html.erb
<h3>Add To-Do Task</h3>
<%= form_with(model: @todo, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Task Name" %>
  </div>
    <div class="field">
    <%= f.label :task %>
    <%= f.text_field :task, required: true, placeholder: "Task Description" %>
  </div>
<!--- find out how to make a dropdown list here -->
    <div>
    <%= f.label :status %>
   <!-- > <%= f.text_field :status, required: true, placeholder: "Status" %> -->
    <%= f.select :status, options_for_select(['Pending','Work in Progress','Done']), {}, {class: 'browser-default'} %> <br>
    </div> 



  <%= f.submit %>
  <% end %>

app/views/todos/show.html.erb
<h1>Todos#show</h1>
<p>Find me in app/views/todos/show.html.erb</p>